services:
  web:
    volumes:
      - ./frontend:/app
      - /app/node_modules

  app:
    volumes:
      - ./backend:/app


  storage:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CORS_ALLOWED_ORIGINS: "*"
      MINIO_CORS_ALLOWED_METHODS: "GET,PUT,POST"
      MINIO_CORS_ALLOWED_HEADERS: "*"

    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
